; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
build_flags = -DPIO_FRAMEWORK_ARDUINO_LITTLEFS -I include
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
monitor_speed = 115200
lib_deps = 
	mandulaj/PZEM-004T-v30@^1.1.2
	plerup/EspSoftwareSerial@^8.2.0
	bblanchon/ArduinoJson@^7.3.0
	links2004/WebSockets@^2.6.1
	mcxiaoke/ESPDateTime@^1.0.4
	knolleary/PubSubClient@^2.8
	enjoyneering/AHT10@^1.1.0
